import = [ "/home/armaan/.config/alacritty/themes/themes/aura.toml" ]
[shell]
args = ['--login']
program = "/usr/bin/zsh"

[cursor]
style = "Beam"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 0
y = 0

#[window.dimensions]
#columns = 90
#lines = 25

